Repository Stephanevg/PSHTML, pull requests merged in 2019-01, with the labels that each got.

#168 Feature charts
  PSHTML/Classes/Public/Chart.ps1
  PSHTML/Examples/Charts/Chart04/4Charts.ps1
  PSHTML/Examples/Charts/Chart04/4graphs.html
  PSHTML/Functions/Public/Clear-WhiteSpace.Ps1
  PSHTML/PSHTML.psd1
  Tests/Chart.BarChart.Tests.ps1
  Tests/Chart.DoughnutChart.Tests.ps1
  Tests/Chart.LineChart.Tests.ps1
  Tests/Chart.New-PSHTMLChart.Tests.ps1
  Tests/Chart.PieChart.Tests.ps1
Labels: Charts

#172 Dev
  CI/02_Install.ps1
  CI/03_Build.ps1
  CI/04_Tests.ps1
  ChartTest.Ps1
  PSHTML/Classes/Private/.gitkeep
  PSHTML/Functions/Public/Get-PSHTMLConfiguration.ps1
  PSHTML/Nested/pshtml.utilities.configuration.psm1
  PSHTML/Nested/pshtml.utilities.logger.psm1
  PSHTML/PSHTML.psd1
  PSHTML/PSHTML.psm1
  PSHTML/pshtml.configuration.json
  TagMigration/CommentBasedHelp.png
  TagMigration/Convert.ps1
  TagMigration/TagMigration.md
  TagMigration/Tag_Template.ps1
  TagMigration/Tag_template.png
  TagMigration/blockquote.ps1
  Tests/Configuration.Tests.Ps1
Labels: enhancement

#182 Feature logging
  CI/03_postContent.ps1
  Code/Classes/001.pshtml.utilities.configuration.ps1
  Code/Classes/002.pshtml.utilities.logging.ps1
  Code/Functions/Private/Get-LogfilePath.Ps1
  Code/Functions/Private/Write-Error.1.ps1
  Code/Functions/Private/Write-PSHTMLLog.ps1
  Code/Functions/Private/Write-Verbose.ps1
  Code/Functions/Private/Write-Warning.ps1
  PSHTML/PSHTML.psm1
  PSHTML/pshtml.configuration.json
  Tests/Configuration.Tests.Ps1
  Tests/Configuration.Unit.Tests.Ps1
Labels: enhancement

#183 Dev
  CI/03_postContent.ps1
  Code/Classes/001.pshtml.utilities.configuration.ps1
  Code/Classes/002.pshtml.utilities.logging.ps1
  Code/Functions/Private/Get-LogfilePath.Ps1
  Code/Functions/Private/Write-Error.1.ps1
  Code/Functions/Private/Write-PSHTMLLog.ps1
  Code/Functions/Private/Write-Verbose.ps1
  Code/Functions/Private/Write-Warning.ps1
  PSHTML/PSHTML.psd1
  PSHTML/PSHTML.psm1
  PSHTML/pshtml.configuration.json
  Tests/Configuration.Tests.Ps1
  Tests/Configuration.Unit.Tests.Ps1
Labels: enhancement

#186 Update 001.pshtml.utilities.configuration.ps1
  Code/Classes/001.pshtml.utilities.configuration.ps1
  PSHTML/PSHTML.psd1
  PSHTML/PSHTML.psm1
Labels: bug

#193 Feature write pshtml asset
  Code/Classes/001.pshtml.utilities.configuration.ps1
  Code/Functions/Public/Add-PSHTMLAsset.ps1
  Code/Functions/Public/Get-PSHTMLAssets.ps1
  Code/Functions/Public/Write-PSHTMLAsset.ps1
  PSHTML/Assets/BootStrap/bootstrap.bundle.js
  PSHTML/Assets/BootStrap/bootstrap.bundle.min.js
  PSHTML/Assets/BootStrap/bootstrap.css
  PSHTML/Assets/BootStrap/bootstrap.min.css
  PSHTML/Examples/Example12/Example12.ps1
  PSHTML/Examples/Example13/Example13.ps1
  PSHTML/Examples/Example14/Example14.ps1
  PSHTML/Examples/Example15/Example15.ps1
  PSHTML/Examples/Example15/Export.html
  PSHTML/PSHTML.psd1
  PSHTML/PSHTML.psm1
  docs/Assets/Assets.md
Labels: bug, enhancement

#195 Dev
  Code/Classes/001.pshtml.utilities.configuration.ps1
  Code/Functions/Public/Add-PSHTMLAsset.ps1
  Code/Functions/Public/Get-PSHTMLAsset.ps1
  Code/Functions/Public/Write-PSHTMLAsset.ps1
  PSHTML/Assets/BootStrap/bootstrap.bundle.js
  PSHTML/Assets/BootStrap/bootstrap.bundle.min.js
  PSHTML/Assets/BootStrap/bootstrap.css
  PSHTML/Assets/BootStrap/bootstrap.min.css
  PSHTML/Examples/Example12/Example12.ps1
  PSHTML/Examples/Example13/Example13.ps1
  PSHTML/Examples/Example14/Example14.ps1
  PSHTML/Examples/Example15/Example15.ps1
  PSHTML/PSHTML.psd1
  PSHTML/PSHTML.psm1
  Tests/Asset.ps1
  docs/Assets/Assets.md
Labels: Assets, enhancement

#196 Dev
  Change_Log.md
  Code/Functions/Public/Get-PSHTMLAsset.ps1
  Code/Functions/Public/Write-PSHTMLAsset.ps1
  PSHTML/PSHTML.psd1
  PSHTML/PSHTML.psm1
  Tests/Asset.ps1
  Tests/Pshtml.Utilities.Assets.Unit.Tests.Ps1
Labels: Assets, Pester Tests, enhancement
